### ISSUE TITLE
데이터 입력 방식

### ISSUE THREAD

**Issue by boy-min** [boy-min/Guitar-Fingering-Generator#1]
main에서 ~note단계까지 import하고, 순서대로 인스턴스를 생성해가며 단계별로 .Append()를 함으로써 입력 데이터를 구축하는 방법과,

music.input(입력값)형태의 함수를 호출하면 music 내부에서 notes 및 note 인스턴스를 만들어 값을 분류, 저장하여 구축하는 형태가 좋을지 고민해봐야 할 것 같습니다.

전자라면 코드 형태가 크게 변하진 않겠지만 import 단계가 조금 지저분해지고,
후자라면 코드 형태가 조금 변하겠지만 import 단계가 비교적 깔끔해질 것입니다.

**Comment by foba1** [comment]
후자가 더 나을것 같다는 생각입니다.
