### ISSUE TITLE
Changes and occurred issues

### ISSUE THREAD

**Issue by foba1** [boy-min/Guitar-Fingering-Generator#14]
commit 내용 : 74db3cdaf81c847a100bfee67e9c572075f6ab63

변경 사항은 아래와 같습니다.
1. Fingering 클래스 제거
2. __set_init_fingering(), __get_distance(), __cal_weight() 함수 Generator 클래스에 추가
3. 테스트를 위해 show() 일시적으로 추가
4. main에 손의 size와 length 입력받는 부분 추가

__set_init_fingering()을 통해 정상적으로 손이 엇갈리지 않는, 하이코드를 고려한 운지법을 설정하는 것까지는 성공하였습니다.
하지만 __cal_weight()를 통해 두 notes 사이로 손가락이 이동하는동안 손에 가해지는 부담을 측정하려고 하였으나(일단은 _get_distance()를 통해 길이만 측정), generate() 함수의 아래와 같은 부분에서 오류가 발생하였습니다.
```py
        for measure in self.__music.get() :
            for notes1 in measure :
                check = False
                for notes2 in measure :
                    if check :
                        print("notes1")
                        notes1.show()
                        print("notes2")
                        notes2.show()
                        print("weight =", self.__cal_weight(notes1, notes2))
                        break
                    if notes1 == notes2 :
                        check = True
                        continue
```
테스트를 위해 notes1과 notes2를 출력하며 weight의 값이 정상적으로 계산되는지 확인하려고 하였는데, 아래와 같은 출력결과를 확인할 수 있었습니다.

![20210526195510](https://user-images.githubusercontent.com/51505940/119648366-55c25580-be5c-11eb-91ed-c1e1ac904535.png)

위 사진과 같이 악보의 초반부에서 항상 두개의 notes가 빈상태로, 정상적으로 출력되지 않았습니다.

![20210526195525](https://user-images.githubusercontent.com/51505940/119648466-74c0e780-be5c-11eb-9788-7f6b2d0ccfb4.png)

또한 위 사진과 같이 notes1이 각 마디의 맨 끝 부분일때 notes2가 빈상태로, 정상적으로 출력되지 않았습니다.

이러한 두 가지 문제가 발생하여 해결책을 찾으려 노력해보았으나 해결 방안을 알 수가 없어 issue에 남깁니다. measure의 형식과 관련된 문제같기는 한데, 아시는 분이 있다면 comment 부탁드립니다.

**Comment by fender2758** [comment]
note가 항상 리스트로 있어서 생긴 문제인거 같습니다.
measure안에 note가 한개씩 있는게 아니라 note가 여러개 묶여 있는 beat가 하나씩 list로 들어있습니다

**Comment by fender2758** [comment]
for measure in self.__music.get() :
            for beat1 in measure :
                check = False
                for beat2 in measure :
                    if check :
		"""
                        print("notes1")
                        notes1.show()
                        print("notes2")
                        notes2.show()
		"""
		for note1 in beat1:
			for note2 in beat2
		                        print("weight =", self.__cal_weight(notes1, notes2))
                        break
                    if notes1 == notes2 :
                        check = True
                        continue

**Comment by fender2758** [comment]
for measure in self.__music.get() :
            for beat1 in measure :
                for beat2 in measure :
                    for note1 in beat1:
                            check = False
                            for note2 in beat2
                                if check :
                                    print("notes1")
                                    notes1.show()
                                    print("notes2")
                                    notes2.show()
                                    print("weight =", self.__cal_weight(notes1, notes2))
                                    break
                                if notes1 == notes2 :
                                    check = True
                                    continue

**Comment by foba1** [comment]
> ```
>     for measure in self.__music.get() :
>         for beat1 in measure :
>             for beat2 in measure :
>                 for note1 in beat1:
>                         check = False
>                         for note2 in beat2
>                             if check :
>                                 print("notes1")
>                                 notes1.show()
>                                 print("notes2")
>                                 notes2.show()
>                                 print("weight =", self.__cal_weight(notes1, notes2))
>                                 break
>                             if notes1 == notes2 :
>                                 check = True
>                                 continue
> ```

beat = notes.__notes 로 이해했는데 맞나요..? 원래의 코드가 연이은 두개의 notes를 앞에서부터 차례대로 비교해서 weight를 출력하는 코드인데, 이 코드를 실행하면 일단 notes1,notes2 에러가 발생하고, 이를 note1,note2로 고쳐 실행해도 TypeError: 'Notes' object is not iterable 가 발생합니다. (for note1 in beat1 부분)

**Comment by foba1** [comment]
해결하였습니다. 감사해요 :)
원인 - for measure in self.__music.get()에서 마디별로 정보를 가져오기에 당연히 마디 마지막 부분에서는 출력이 안됨. 또한 악보 데이터에 쉼표 정보도 포함되어 twilight.gp5를 사용할 경우 초반의 쉼표 두개가 존재하여 출력이 안됨.
