### ISSUE TITLE
구조 변경, 전체적인 이름 수정

### ISSUE THREAD

**Issue by boy-min** [boy-min/Guitar-Fingering-Generator#3]
foba1-develop 브랜치를 boymin-develop 브랜치에 머지하였고,
일부 내용 수정 후 boymin-develop에 push하였습니다.

변경 내용

1. 전체적인 폴더명 스타일 변경
  Folder -> folder 꼴로, PEP-8 스타일로 이름 변경하였습니다.

2. 전체적인 함수 이름 스타일 변경
  FunctionName -> function_name 꼴로, PEP-8 스타일로 이름 변경하였습니다.

3. 전체적인 클래스 이름 스타일 변경
  class -> Class 꼴로, PEP-8 스타일로 이름 변경하였습니다.

4. 전체적인 함수명 변경, 통합
  GetNote, GetNotes, GetMusic, ... 등 Get시리즈를 모두 get()으로,
  SetNote, SetNotes, SetMusic, ... 등 Set시리즈를 모두 set()으로 통합하였습니다.

5. __init__ 변경
  전체적으로 수정이 이루어졌습니다.
  생성자에 디폴트 값(대체적으로 None)을 갖는 매개변수들을 추가함으로써,
  추가적으로 set()을 호출하지 않고 생성자에서 바로 값을 넣어버리는 형태도 가능하도록 변경하였습니다.
  note, notes, music, generator 생성자가 해당 변경점이 반영되었습니다.

6. get() 리턴값 변경
  대대적으로 수정이 이루어졌습니다.
  note의 경우 string, self, finger를 딕셔너리로 묶어서 반환합니다. 매개변수로 key를 입력하면 해당하는 값만을 반환합니다.
  hand의 경우도 size, length를 딕셔너리로 묶어서 반환합니다. 매개변수로 key를 입력하면 해당하는 값만을 반환합니다.
  notes, music, generator, fingering은 순서대로 self.__notes, self.__music, self.__music, self.__fingering을 그대로 반환합니다.
    리스트로 묶어서 반환하지 않는 이유는, 하위 클래스의 함수들을 사용할 수 없을 뿐더러,
    리스트를 애써 클래스로 변환해놨는데 다시 리스트로 묶어서 반환할 필요가 없기 때문입니다.

7. show() 함수
  printer의 print_sheet 함수명을 show()로 바꿨습니다.
  5번에 의해 get()이 객체의 리스트를 반환할 수도 있게 됨으로써,
  대부분의 클래스에 show() 함수를 추가하고 하위 클래스의 show()를 호출시키는 구조로 변경하였습니다.
  또한, 별도의 매개변수를 지정해주지 않으면 전체를 출력해주는 기능도 추가하였습니다.
  이 기능은 다른 클래스의 show()함수에도 반영되어 있습니다.

8. 그 외 변경사항
  1 모든 오류를 sys.exit(에러 내용) 꼴로 변경하였습니다.
  2 notes에서 하던 note의 parameter error 체크를 note에서 하도록 변경하였습니다.
  3 note에 __eq__를 추가하여, string과 fret으로 비교하는 과정을 쉽게 바꾸었습니다.
  4 notes, music의 set()을 [기존 리스트에 append] 에서 [새로운 리스트 생성]으로 바꿨고, 동시에 형태를 조금 단순화했습니다.
  5 generator에서 하던 fingering에 기본 코드를 넣는 과정을 fingering의 생성자에서 하도록 변경하였습니다.
  6 대부분의 i, j, k를 note_, notes_, music_ 등 의미를 갖는 이름으로 변경하였습니다.
  7 music_sheet, note_list, self.__list 등의 이름을 music_, notes_ 등으로 단순화하였습니다.
  8 enumerate를 이용하여 fingering.__find_similar_code, show 함수에서 인덱스를 가져오는 부분을 단순화하였습니다.
  9 main의 printer를 p로 import 해오던걸 다시 printer로 import하였고, show()의 전체출력 테스트 구문을 추가했습니다.
  10 생성자, get, set 등의 변경으로 전체적으로 관련 코드 부분이 변경되었습니다.

토론해봐야할 내용

기존 코드 구조와 새로운 코드 구조 중에 어떤 구조가 더 이상적일 지 생각해봐야할 것 같습니다.
주요 변경점은 4, 5번 항목입니다. 어느쪽이든 장단점이 있다고 생각합니다.
기존 구조는 리스트를 빠르게 가져올 수 있어서 출력하기는 편하지만, 클래스 구조가 애매해지는 부분이 있습니다.
새로운 구조는 리스트 자체에 접근하려면 get()을 조금 더 써야할 수는 있지만(단순 출력을 위한 부분은 show()로 해결),
비교적 클래스 구조가 명확하고 코드가 깔끔합니다.

차후 개발에 대하여

앞으로 폴더명, 함수명 등은 [PEP-8](https://www.python.org/dev/peps/pep-0008/)을 따르기로 하는 것이 좋을 것 같습니다.
간략하게 설명하면,
폴더명은 모두 소문자로, 가능하면 짧게, 필요에 따라 _ 사용 가능하지만 권장하지 않음
클래스명은 CapWords 규칙
함수명은 모두 소문자로, 필요에 따라 _ 사용 가능
정도입니다. 자세한 내용은 링크 혹은 구글링을 참고하시면 될 것 같습니다.

fingering의 __find_similar_code, generator의 generate 부분을 제외한 나머지 부분은 물론 기능들이 계속 추가되어야 하겠지만,
작성된 부분은 얼추 완성되어간다는 생각이 듭니다.
(물론 아직까지도 _find_similar_code 부분이 이상적인 결과를 내는 것인지는 모르겠습니다.
일단은 내용 변경 없이 새로운 구조에 맞게 구조 변경만 해두었습니다.)
기존 구조나 새로운 구조 중 어느 하나로 결정을 낸다면,
main 브랜치에 merge하고, 위 두 기능들을 포함한 추가 기능들을 분배하여 각자 develop 브랜치를 파서 코드를 작성하고,
main 브랜치에 Pull Request를 한 뒤 모두가 어느정도 검토하면 main에 merge하는 식으로 개발하면 될 것 같습니다.
최종적으로는 release branch를 만들어, main 브랜치를 merge하는 식으로 진행하면 될 것 같습니다.

**Comment by foba1** [comment]
None type에 접근하는 오류가 있어 수정하였고, Fingering class의 append, delete 함수를 private으로 변경하였습니다. (Generator에서 이를 관리하는것은 올바르지 않은 것 같습니다.)

함수명이나 변수명 같은 부분은 통일이 필요하다고 생각했었는데, 직접 해주신 것에 감사드립니다.

_find_similar_code 의 경우 아직 문제가 많습니다. count를 측정하는 방식에도 기타 줄의 번호와 프렛 번호가 모두 같은 경우에 한해서만 확인한다는 문제가 있고, 각 기타 코드별 우선순위도 올바르게 적용되어 있지 않은 상황입니다.

변경해 주신 코드들은 모두 확인해보았는데, 이전의 구조보다는 바꾸어주신 구조가 훨씬 명확한 느낌이 듭니다. 크게 더 바꾸어야할 부분이 없다면 main에 merge해도 괜찮을 것 같습니다.
